import type { Metadata } from "next";
import "./globals.css";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";

const inter = Inter({
  weight: ["300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Centrum vôľa žiť",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sk">
      <AppRouterCacheProvider>
        <body className={`${inter.className} antialiased`}>
          <Navbar /> {children}
        </body>
      </AppRouterCacheProvider>
    </html>
  );
}
