import type { Metadata } from "next";
import "./globals.css";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import HydrationZustand from "./components/HydrationZustand";
import { ThemeProvider } from "@mui/material/styles";
import theme from "./lib/theme";

const inter = Inter({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Centrum vôľa žiť",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="sk">
      <AppRouterCacheProvider>
        <body className={`${inter.className} antialiased`}>
          <HydrationZustand>
            <ThemeProvider theme={theme}>
              <Navbar /> {children}
              <Footer />
            </ThemeProvider>
          </HydrationZustand>
        </body>
      </AppRouterCacheProvider>
    </html>
  );
}
