name: Build and Deploy Distroless Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
      NEXT_PUBLIC_USER_POOL_ID: ${{ secrets.NEXT_PUBLIC_USER_POOL_ID }}
      NEXT_PUBLIC_USER_POOL_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_USER_POOL_CLIENT_ID }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push distroless Docker imagee
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --build-arg ACCESS_KEY_ID=$ACCESS_KEY_ID \
            --build-arg SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY \
            --build-arg NEXT_PUBLIC_USER_POOL_ID="$NEXT_PUBLIC_USER_POOL_ID" \
            --build-arg NEXT_PUBLIC_USER_POOL_CLIENT_ID="$NEXT_PUBLIC_USER_POOL_CLIENT_ID" \
            --build-arg RESEND_API_KEY="$RESEND_API_KEY" \
            -t xkolumber/centrumvz-distroless-image:${{ github.run_number }} \
            --push .

      - name: Set up SSH private key
        run: |
          echo "${{ secrets.CONTABO_KEY }}" > contabo_key.pem
          chmod 600 contabo_key.pem

      - name: Deploy to Contabo VPS
        env:
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          NEXT_PUBLIC_USER_POOL_ID: ${{ secrets.NEXT_PUBLIC_USER_POOL_ID }}
          NEXT_PUBLIC_USER_POOL_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_USER_POOL_CLIENT_ID }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          IMAGE_TAG: ${{ github.run_number }}
        run: |
          echo "Running deploy with image tag: $IMAGE_TAG"

          cat << EOF > deploy.sh
            docker pull xkolumber/centrumvz-distroless-image:$IMAGE_TAG
            docker stop centrumvz-container || true
            docker rm centrumvz-container || true
            docker run -d \
              --name centrumvz-container \
              --restart=always \
              -p 3000:3000 \
              -e ACCESS_KEY_ID="$ACCESS_KEY_ID" \
              -e SECRET_ACCESS_KEY="$SECRET_ACCESS_KEY" \
              -e NEXT_PUBLIC_USER_POOL_ID="$NEXT_PUBLIC_USER_POOL_ID" \
              -e NEXT_PUBLIC_USER_POOL_CLIENT_ID="$NEXT_PUBLIC_USER_POOL_CLIENT_ID" \
              -e RESEND_API_KEY="$RESEND_API_KEY" \
              xkolumber/centrumvz-distroless-image:$IMAGE_TAG

              docker images "xkolumber/centrumvz-distroless-image" --format "{{.Repository}}:{{.Tag}}" \
                | grep -v ":$IMAGE_TAG" \
                | xargs -r docker rmi || true
          EOF

          chmod +x deploy.sh
          scp -i contabo_key.pem -o StrictHostKeyChecking=no deploy.sh deployuser@89.117.58.203:/home/deployuser/deploy.sh
          ssh -i contabo_key.pem -o StrictHostKeyChecking=no deployuser@89.117.58.203 'bash /home/deployuser/deploy.sh'
